Go 中，错误用内建的 `error` 类型来表示。

就像其他的内建类型（如 `int`、`float64` 等），错误值可以存储在变量里、作为函数的返回值等等。
```go
func main() {  
    f, err := os.Open("/test.txt")   //打开不存在的文件
    if err != nil {          //如果 error 不为 nil，也就是发生了错误
        fmt.Println(err)
        return
    }
    fmt.Println(f.Name(), "opened successfully")
}
```
其中 `os` 包中的 `Open` 函数签名为
```go
func Open(name string) (file *File, err error)
```
如果成功打开文件，`Open` 函数会返回一个文件句柄和一个值为 `nil`的错误(error)。而如果打开文件时发生了错误，会返回一个不等于 `nil` 的错误。

如果一个函数 或方法 返回了错误，按照惯例，错误作为最后一个值返回。`Open` 函数也是将 `err` 作为最后一个返回值。

Go 的惯例，在处理错误时，通常是将返回的错误与 `nil` 比较。`nil` 表示没有错误发生，非 `nil` 表示出现了错误。

程序输出
```go
open /test.txt: No such file or directory
```
## 错误类型的表示
`error` 是一个接口类型
```go
type error interface {  
    Error() string      //接口中的方法签名
}
```
`error` 有了一个签名为 `Error() string` 的方法。所有实现该接口的类型都可以当作一个错误类型。`fmt.Println` 打印错误时，会在内部调用 `Error() string` 方法来输出该错误的描述。
## 从错误获取更多信息的不同方法
不同的方法获取发生错误的文件名
### 1. 断言底层结构体类型，使用结构体字段获取更多信息
 `Open` 函数返回的错误类型是 `*PathError`，`PathError` 是结构体类型。
 ```go
 type PathError struct {  
    Op   string
    Path string
    Err  error
}

//PathError 实现了 error 接口，就属于 error 类型，可以将值传给 error
func (e *PathError) Error() string { return e.Op + " " + e.Path + ": " + e.Err.Error() }  //Error() string 将文件操作、路径和实际错误拼接，并返回该字符串。
```
结构体 `PathError` 的 `Path` 字段，就有错误的文件路径。修改前面的程序，打印出该路径。
```go
func main() {  
    f, err := os.Open("/test.txt")s
    if err, ok := err.(*os.PathError); ok {   //使用类型断言获取 error 接口的底层值，如果error接口为nil，则 ok=false，没有错误，如果底层类型为 PathError，则有错误，err 为 PathError 类型的值，通过 err.Path 获取 PathError 中的 Path
        fmt.Println("File at path", err.Path, "failed to open")   //使用 err.Path 来打印该路径。
        return
    }
    fmt.Println(f.Name(), "opened successfully")  //File at path /test.txt failed to open
}
```
可以看到，断言接口的底层结构体类型，如果没有发生 `error`，则底层结构体为 `nil`，`ok` 为 `false`，如果发生 `error` 则获取到底层错误有关结构体类型的值，这个值中包含了错误信息。此例中 `Open` 返回的错误类型是 `*PathError`，则断言 `*PathError` 这个底层结构体类型，如果断言到这个结构体类型的值，则获取这个值中的信息。
### 2. 断言底层结构体类型，调用方法获取更多信息
标准库中的 `DNSError` 结构体类型定义如下：
```go
type DNSError struct {  
    ...
}

func (e *DNSError) Error() string {  
    ...
}
func (e *DNSError) Timeout() bool {    //返回 bool 值
    ... 
}
func (e *DNSError) Temporary() bool {  //返回 bool 值
    ... 
}
```
编写程序，断言 `*DNSError` 类型，并调用这些方法来确定该错误是临时性错误，还是由超时导致的。
```go
func main() {  
    addr, err := net.LookupHost("golangbot123.com")
    if err, ok := err.(*net.DNSError); ok {    //断言 *net.DNSError 的类型，获取到了错误的底层值。
        if err.Timeout() {     //调用
            fmt.Println("operation timed out")
        } else if err.Temporary() {
            fmt.Println("temporary error")
        } else {
            fmt.Println("generic error: ", err)   //generic error: lookup golangbot123.com: no such host
        }
        return
    }
    fmt.Println(addr)
}
```
### 3. 直接比较
第三种获取错误的更多信息的方式，是与 `error` 类型的变量直接比较。

`filepath` 包中的 `Glob` 用于返回满足 `glob` 模式的所有文件名。如果模式写的不对，该函数会返回一个错误 `ErrBadPattern`。

`filepath` 包中的 `ErrBadPattern` 定义如下：
```go
var ErrBadPattern = errors.New("syntax error in pattern")
```
`errors.New()` 用于创建一个新的错误，当模式不正确时，`Glob` 函数会返回 `ErrBadPattern`。
```go
func main() {  
    files, error := filepath.Glob("[")
    if error != nil && error == filepath.ErrBadPattern {  //将 error 直接与 filepath.ErrBadPattern 相比较。如果该条件满足，那么该错误就是由模式错误导致的。
        fmt.Println(error)   //syntax error in pattern
        return
    }
    fmt.Println("matched files", files)
}
```
## 不可忽略错误
绝不要忽略错误。忽视错误会带来问题，错误一定要解决。